Algoritmo "semnome"

Var
opcao:inteiro
Inicio
escreval("Digite '1', para praia")
escreval("Digite '2', para cinema")
escreval("Digite '3', para churrasco")
leia (opcao)
escolha opcao
caso 1
escreval ("sair de casa as 8 horas da manha.")
caso 2
escreval ("sair de casa as 2 horas da tarde.")
caso 3
escreval ("sair de casa ao meio-dia.")
outrocaso
escreval ("ja que nao optou,fique em casa mesmo e leia um livro.")
fimescolha
Fimalgoritmo